### ISSUE TITLE
[FEATURE]: Clean up roadmap

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-io-website#68] opened 2024-06-11 17:15 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### New feature

Let's update it to reflect the fact we are almost in Q3 and include the milestones that we've already accomplished. Let's improve the accuracy by putting items that are beyond 2024 in a subsequent section called "And Beyond...".

See internal roadmap document.

**Comment by jredbeard** [comment] 2024-06-11 17:34
Duplicate of #28 but with more information, can close #28 if you want @sgerbino

**Closed** 2024-06-26 21:21 UTC
Labels: enhancement
